### ISSUE TITLE
Invalid display: flex css prefixed property

### ISSUE THREAD

**Issue by beatlecz** [robinweser/react-layout-components#30]
Box not working because of invalid display:flex prefixed properties 
[https://www.dropbox.com/s/49vppak8izq6rce/Screenshot%202016-05-06%2013.09.17.png?dl=0](url)

**Comment by beatlecz** [comment]
After some lurking into code I found out the instant solution. The problem is in prefix library. You can just set the version of library to equal 1.0.1 , then it works.

**Comment by robinweser** [comment]
Thanks for reporting. Actually this is a dublicate of #27 (at least the same problem)
Actually there is no problem with the prefix library (which by the way is written by myself as well). React just does not support compatible CSS strings as inline styles anymore. Still I found a solution which will be added soon. I will close this one, further discussion in #27 again.

**Comment by alecf** [comment]
I also found that the problem was in the prefix library, specifically https://github.com/rofrischmann/inline-style-prefix-all/pull/7 - I think that PR makes it so that `{ display: 'flex' }` becomes `display: flex,-webkit-flex,-ms-flexbox,-moz-box,-webkit-box` which is invalid CSS. previously it would become `display: flex;display:-webkit-flex;display:-ms-flexbox;display:-moz-box;display:-webkit-box` which would correctly fall back.

I also found that pinning inline-style-prefix-all to 1.0.5 fixed the problem for me, but obviously that's not a great solution.

**Comment by robinweser** [comment]
@alecf The prefixer actually never returned the comma seperated values as this PR was not released before the fixed was pushed as well. While 1.0.5 works with React 14.x it does not work with 15+ which is why the prefixer was updated to output arrays for later processing. 
The prefixer actually returns the right values, but React's new rendering mechanism does not allow fallback values at all. That's why the display:flex is not assigned properly and the Box fails.

I already know how to fix it, but yet am trying how to do it as elegant as possible.
Expect a working release to be done this evening, with 14.x and 15+ support.

**Comment by oallouch** [comment]
Thx
Waiting for it.
Your lib is so useful.
